version: "3"
services:
  weibo-rss:
    image: einverne/docker-h5ai
    container_name: h5ai
    restart: always
    expose:
      - 80
    volumes:
      - /var/www/drive:/var/www
    environment:
      VIRTUAL_HOST: file.einverne.info
      VIRTUAL_PORT: 80

networks:
  default:
    external:
      name: nginx-proxy
